### ISSUE TITLE
Sorting by oblast on MPs page

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip#147] opened 2015-12-04 07:28 UTC
Looks like here https://tvfy-ukraine.oaf.org.au/people?sort=constituency
it sorts by constituency number, not oblast title. Can we change sorting from constituency number to oblast? Or even better to sort by constituency and on MPs preview show their oblast like in #59??

One more thing. Seems like sorting works by two first digits so 159 goes before 160
Am I correct?

**Comment by henare** [comment] 2015-12-07 01:56
This would be fixed by doing https://github.com/openaustralia/ukraine_verkhovna_rada_deputies/issues/6 because then the "constituency" field in our database would be the oblast name instead of the far less helpful district number.

**Comment by henare** [comment] 2015-12-07 02:02
Closing this because we should do https://github.com/openaustralia/ukraine_verkhovna_rada_deputies/issues/6 to fix it.

**Comment by henare** [comment] 2015-12-07 07:15
I've deployed the changes, please reopen this if it's still a problem.

**Comment by lisoffsky** [comment] 2015-12-07 17:29
I'm sorry,
The order is good for English language but has less sense for Ukrainian. 
I suppose that's again an issue of sorting by translated oblast titles just like in #148 

Can this be somehow fixed? I can give a table of ukr-eng oblast titles if needed

**Comment by beastie87** [comment] 2015-12-07 17:56
m.constituency  is English or Ukrainian ? 
maybe
if m.constituency is Ukrainian 
not use transliterate

**Comment by henare** [comment] 2015-12-08 00:00
@beastie87 good thinking. However, constituency is Ukrainian but the Ruby sort function doesn't sort properly with Ukrainian. We need to find another way to sort.

**Comment by henare** [comment] 2015-12-08 03:02
Now that we've defined this problem, I'm closing it as a duplicate of #148 because we'll fix the Ukrainian sort order problem there.

**Closed as completed by henare** 2015-12-08 03:02 UTC
Labels: bug, backend
